(function(){
  const s=document.createElement('style');
  s.id='edm-premium-home';
  s.textContent=`
  .premium-home{display:grid;gap:18px;margin-top:18px}.premium-block{padding:26px;border:1px solid #586872;border-radius:24px;background:linear-gradient(145deg,#253139,#182126);box-shadow:0 18px 44px rgba(0,0,0,.22)}.premium-head{text-align:center;margin-bottom:22px}.premium-head small{color:#e09a69;font-weight:900;letter-spacing:.14em;text-transform:uppercase}.premium-head h2{margin-top:8px;color:#fff!important;font-size:clamp(1.8rem,3vw,2.6rem)}.premium-head p{max-width:700px;margin:10px auto 0}.premium-steps{display:grid;grid-template-columns:repeat(5,1fr);gap:12px}.premium-step{padding:18px 14px;text-align:center;border:1px solid rgba(224,154,105,.25);border-radius:18px;background:linear-gradient(145deg,#1f2a30,#131b1f)}.premium-icon{width:48px;height:48px;margin:0 auto 13px;display:grid;place-items:center;border-radius:15px;border:1px solid rgba(224,154,105,.36);color:#f0b389;background:rgba(216,141,93,.1);font-weight:900}.premium-step b{display:block;color:#fff!important;margin-bottom:6px}.premium-step p{margin:0;font-size:.86rem}.premium-trust{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.premium-trust article{padding:18px;border:1px solid rgba(224,154,105,.22);border-radius:18px;background:linear-gradient(145deg,#202b31,#151d21)}.premium-trust b{color:#fff!important;text-transform:uppercase;font-size:.84rem}.premium-trust p{margin:7px 0 0;font-size:.88rem}.premium-cta{display:flex;align-items:center;justify-content:space-between;gap:18px;padding:24px 28px;border-radius:22px;background:linear-gradient(110deg,#c17b50,#84472c 60%,#35251f);box-shadow:0 20px 44px rgba(80,38,20,.3)}.premium-cta h3{color:#fff!important}.premium-cta p{margin:6px 0 0;color:#f2ddd0!important}.premium-cta button{background:#101619!important;color:#fff!important}.hero h1{text-transform:uppercase}.hero-grid{grid-template-columns:minmax(0,1.2fr) minmax(290px,.8fr)!important}@media(max-width:1100px){.premium-steps{grid-template-columns:repeat(3,1fr)}.premium-trust{grid-template-columns:repeat(2,1fr)}}@media(max-width:720px){.premium-steps,.premium-trust{grid-template-columns:1fr}.premium-cta{flex-direction:column;align-items:stretch}.premium-cta button{width:100%}}
  `;
  document.head.appendChild(s);
  function init(){
    const q=x=>document.querySelector(x);
    const e=q('#home .eyebrow');if(e)e.textContent='EDM - Specialiste du freinage';
    const h=q('#home h1');if(h)h.innerHTML='Votre securite,<br>notre expertise.';
    const l=q('#home .lead');if(l)l.textContent='Specialiste du freinage et de l entretien automobile. Preparez une demande precise, consultez une estimation transparente et beneficiez d une validation humaine.';
    const b=document.querySelectorAll('#home .btn-row .btn');if(b[0])b[0].textContent='Demander une estimation';if(b[1])b[1].textContent='Voir le fonctionnement';
    const stats=document.querySelectorAll('#home .hero-stat');const v=[['01','Diagnostic precis','Decrivez le vehicule et les symptomes.'],['02','Tarifs transparents','Visualisez la main d oeuvre et les pieces estimees.'],['03','Validation EDM','Chaque demande est verifiee avant confirmation.']];stats.forEach((x,i)=>{if(v[i])x.innerHTML='<span>'+v[i][0]+'</span><div><b>'+v[i][1]+'</b><p>'+v[i][2]+'</p></div>'});
    const home=q('#home');if(!home||q('.premium-home'))return;
    const wrap=document.createElement('div');wrap.className='premium-home';
    wrap.innerHTML='<section class="premium-block"><div class="premium-head"><small>Parcours client</small><h2>Comment ca marche</h2><p>Un processus simple pour preparer votre demande avant la validation finale par EDM.</p></div><div class="premium-steps"><article class="premium-step"><div class="premium-icon">1</div><b>Votre vehicule</b><p>Renseignez les informations utiles.</p></article><article class="premium-step"><div class="premium-icon">2</div><b>Vos besoins</b><p>Selectionnez les prestations souhaitees.</p></article><article class="premium-step"><div class="premium-icon">3</div><b>Estimation</b><p>Consultez les prix et niveaux de pieces.</p></article><article class="premium-step"><div class="premium-icon">4</div><b>Transmission</b><p>Envoyez votre demande complete.</p></article><article class="premium-step"><div class="premium-icon">5</div><b>Validation</b><p>EDM controle avant confirmation.</p></article></div></section><section class="premium-block"><div class="premium-head"><small>L engagement EDM</small><h2>Pourquoi choisir EDM</h2></div><div class="premium-trust"><article><b>Expertise freinage</b><p>Une approche centree sur la securite.</p></article><article><b>Pieces adaptees</b><p>Trois niveaux selon qualite et budget.</p></article><article><b>Transparence</b><p>Une estimation detaillee et lisible.</p></article><article><b>Suivi humain</b><p>Chaque demande est controlee manuellement.</p></article></div></section><section class="premium-cta"><div><h3>Preparez votre demande maintenant</h3><p>Renseignez votre vehicule et obtenez une premiere estimation.</p></div><button class="btn" type="button">Commencer ma demande</button></section>';
    wrap.querySelector('button').onclick=()=>q('[data-page="appointment"]')?.click();home.appendChild(wrap);
  }
  window.addEventListener('load',init);setTimeout(init,350);
})();
